zeno-ml/zeno

frontend/src/global.d.ts, frontend/src/instance-views/InstanceView.svelte, frontend/src/instance-views/ListView.svelte, frontend/src/instance-views/TableView.svelte
This arose from Issue #453. 
I was confused for a bit, hopefully this helps someone else in the future. 
The types can be more specific, but I'm not "in the know"
Check out `global.d.ts` for the bulk of the changes
=> feat: add type to view function component

README.md
=> Fix intro link in readme

frontend/public/global.css, frontend/src/Explore.svelte, frontend/src/general/Header.svelte, frontend/src/metadata/MetadataPanel.svelte, frontend/src/metadata/SelectionBar.svelte, frontend/src/metadata/cells/FolderCell.svelte, frontend/src/metadata/cells/MetadataCell.svelte, frontend/src/metadata/cells/SliceCell.svelte
Slight changes to make the frontend match wireframes more and make things more cohesive.
=> Frontend: slightly changed colors, font sizes, and spacing 

DEVELOPMENT.md, Makefile
Add Windos OS notes and update Makefile.
=> Windows OS Note

frontend/src/instance-views/scatter-view/ScatterLegend.svelte, frontend/src/instance-views/scatter-view/regl-scatter/colors.ts
=> fix: boolean colors reverse

DEVELOPMENT.md
=> docs: add standard for commit messages

frontend/src/report/ReportsList.svelte
=> fix: change to new report when creating it

examples/imagenette/README.md, examples/imagenette/tests/loading.py, examples/imagenette/tests/metrics.py, examples/imagenette/tests/zeno.toml
also very fast now, inference on 2 resnet models take ~12 min compared to ~1 hour for me before
=> fix: imagenette example works again

frontend/src/metadata/popups/FilterEntry.svelte
With the new select component from the svelecte library, the boolean values for the filterentry component were not loading in. This should fix that issue.
=> fix: boolean filterentry fix

frontend/src/api/table.ts, frontend/src/instance-views/ListView.svelte, frontend/src/instance-views/TableView.svelte, frontend/src/instance-views/instance-views.ts, frontend/src/instance-views/scatter-view/ScatterView.svelte, frontend/src/zenoservice/models/ZenoSettings.ts, zeno/backend.py, zeno/classes/classes.py, zeno/runner.py, zeno/server.py, zeno/util.py
This will make it possible to save new instances locally to cache for gradio integration
=> feat: pass instances with path directly to views

.vscode/launch.json, Makefile, zeno/__init__.py, zeno/api.py, zeno/backend.py, zeno/processing/data_processing.py, zeno/server.py
Revamp the decorator API to have typed returns. Helps significantly with auto type hints and validation.
Downside is it is a bit more complicated to learn, but not as complicated as guessing at return types IMO.
=> feat: typed returns for functions

DEVELOPMENT.md
Updated the README.md file for compatibility issues with M-1 chip Apple laptop and forking mechanisms.
=> feat: update development markdown file for details on fixing M-1 chip complications

frontend/src/api/slice.ts, frontend/src/api/table.ts, frontend/src/instance-views/scatter-view/scatter.ts, frontend/src/metadata/MetadataPanel.svelte, frontend/src/metadata/cells/metadata-cells/TextMetadataCell.svelte, frontend/src/metadata/popups/FilterEntry.svelte, frontend/src/metadata/popups/NewSlicePopup.svelte, zeno/backend.py, zeno/processing/data_processing.py, zeno/processing/filtering.py, zeno/processing/histogram_processing.py
Also adds cached calls to slice metrics
=> fix: fix model naming, regex search, other bugs

frontend/src/metadata/MetadataPanel.svelte, frontend/src/util/util.ts
Change the model and metric select to a regular select to fix rendering issues.
=> style: fix select on metadata panel

frontend/src/report/report-page/encoding/Encoding.svelte, frontend/src/report/table-report/SliceDetailsContainer.svelte, frontend/src/report/table-report/TableReportRow.svelte, frontend/src/report/table-report/TableReportTable.svelte
1. Refactor Table view encoding to make it more easier for users to understand how to fix the 3rd dimension
2. Refactor Table design to make it more aligned
3. Add sort feature to sort by column values
4. fix minor bugs when clicking slice detail container
=> refactor: Report table view

frontend/src/report/table-report/TableReportRow.svelte, frontend/src/report/table-report/TableReportTable.svelte
This PR moves the fixed column in the chart table view to the top line
=> refactor: move fixed column to the top line

frontend/src/metadata/SelectionBar.svelte, frontend/src/metadata/cells/TagCell.svelte, frontend/src/metadata/chips/SliceChip.svelte, frontend/src/metadata/chips/TagChip.svelte
This PR gives more border radius on tag-related cells & chips to display more obvious difference between tags and slices.
=> refactor: update tags style to differentiate more from slices and predicates

frontend/src/Comparison.svelte, frontend/src/api/table.ts, frontend/src/instance-views/ComparisonView.svelte, frontend/src/metadata/MetadataPanel.svelte, frontend/src/metadata/cells/SliceFinderCell.svelte, frontend/src/metadata/popups/SliceFinderPopup.svelte, frontend/src/zenoservice/models/SliceFinderRequest.ts, frontend/src/zenoservice/models/TableRequest.ts, zeno/backend.py, zeno/classes/classes.py, zeno/classes/slice_finder.py, zeno/processing/slice_finder.py, zeno/util.py
This PR enhances the comparison tab by adding support for slicefinder, which allows users to find slices with the highest difference in metrics between two models. Additionally, it includes updates to various slice finder styles.
=> feat: slice finder in comparison tab and style update

frontend/src/metadata/MetadataPanel.svelte, frontend/src/metadata/cells/FolderCell.svelte, frontend/src/metadata/popups/NewFolderPopup.svelte, frontend/src/stores.ts
This PR supports renaming folders.
=> feat: rename folder

frontend/src/metadata/cells/FolderCell.svelte, frontend/src/metadata/cells/SliceCell.svelte
This PR introduces a new functionality that enables the simultaneous dragging of multiple slices into a folder.
=> feat: multiple slices dragging at the same time

frontend/src/Comparison.svelte, frontend/src/metadata/MetadataPanel.svelte, frontend/src/metadata/cells/SliceCell.svelte
=> feat: show slice edit popup even when in compare view

frontend/src/metadata/popups/SliceFinderPopup.svelte
This PR resolves issues below by:
1. adding more details on alpha tooltip
2. modify the tooltip and naming of metric column and order by column
=> fix: issues regarding slice finder

frontend/src/Comparison.svelte, frontend/src/metadata/MetadataPanel.svelte
=> feat: show new slice and new folder buttons in compare as well

frontend/src/metadata/chips/MetadataChip.svelte
This PR fix a minor bug of nomial metadata chip mis-using string-search format.
=> fix: nomial metadata chip mis-using string-search format
